server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.92.117:3306/db_qfnu_test
    username: db_qfnu_test
    password: "db_qfnu_test"
  jpa:
    hibernate:
      ddl-auto: update #在生产环境常用none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database: mysql
